### ISSUE TITLE
Construct the bayes net from the maximum spanning tree

### ISSUE THREAD

**Issue by mjs2600** [mjs2600/mimicry#10]

**Comment by jlmcgehee21** [comment]
Created a Bayes' net from spanning tree with UNCONDITIONAL probabilities on each node.  Stuck on how to generate directed path to find conditional probabilities.

Do we just have to pick a root and iterate through all the connections?  There has to be a better way I'm missing.

I did try experimenting with ng.all_simple_paths() but the best method for use wasn't super clear to me.

**Comment by jlmcgehee21** [comment]
@mjs2600 If you check the math and make sure it seems right to you, we can check this off.  I calculated a few of the probabilities by hand and they seemed to line up with the code

**Comment by mjs2600** [comment]
@jlmcgehee21 I'll double check it. Can you look at #6 for me?

**Comment by mjs2600** [comment]
Looks great!
