### ISSUE TITLE
mimcry.mimic.Mimic.fit() return Error

### ISSUE THREAD

**Issue by jclentini** [mjs2600/mimicry#16]
mimcry.mimic.Mimic.fit() returning TypeError: fit() takes exactly 1 arguments (2 given) even though only one is given. Please advise.

**Comment by jlmcgehee21** [comment]
How are you calling the fit function?  The error seems pretty self explanatory.

**Comment by jclentini** [comment]
Jeff, yes, that is what I thought too. I a using your code from bitbucket: https://bitbucket.org/jeff_mcgehee/project2ml/src  The mimicry code is called from OptimizationSimulations.py. All three Fitess functions generate the same error.

**Comment by jclentini** [comment]
Here is the Traceback:

GA Complete
SA Complete
RHC Complete

Traceback (most recent call last):
  File "/home/jclentini/Documents/john/OptimizationSimulations.py", line 227, in <module>
    knapsack_sim()
  File "/home/jclentini/Documents/john/OptimizationSimulations.py", line 41, in knapsack_sim
    mim.fit(50)
TypeError: fit() takes exactly 1 argument (2 given)

**Comment by jlmcgehee21** [comment]
Oh. Ok, that code is a mess :smile: It uses a different branch of Mimicry: https://github.com/mjs2600/mimicry/tree/jeff_ml_project_2

**Comment by jclentini** [comment]
Makes sense, your saying use the branch in the link above? I'll get this running with the code from the branch above then I'll go back and try to tweak the code to get it running in the current branch of mimicry. Thank for your help. If I run into problems, I'll post again.

**Comment by jlmcgehee21** [comment]
My code from bitbucket uses the branch above as a dependency rather than the master branch of Mimicry.  So if you want the code for OMSCS project 2 that I have in bitbucket to run as it is designed to, you need to use the branch I mentioned.

**Comment by jclentini** [comment]
Fyi, code is working fine but, man this MIMIC algorithm takes a long time. By chance do you have any experience optimizing flight itineraries?

**Comment by jlmcgehee21** [comment]
No, sorry. Honestly that mimicry code was hacked together, by myself and @mjs2600.  There's still a lot to be done in terms of robustness, flexibility, and speed.

That being said, one of the greatest downfalls of the MIMIC algo itself is computation time per fitness evaluation.  Ideally, it is able to make up for this deficiency by converging in many fewer iterations than other algorithms.  iirc, I had to cut MIMIC off in my paper and compare it with the other algorithms based on efficiency (solution quality vs. number of fitness evals).  That's all I really feel like I should say without helping you too much on your assignment :wink:

**Comment by jclentini** [comment]
Thank you. Appreciate the input.

**Comment by mjs2600** [comment]
Can this be closed?

**Comment by jclentini** [comment]
Yes
