### ISSUE TITLE
Construct the mutual information graph

### ISSUE THREAD

**Issue by mjs2600** [mjs2600/mimicry#4]

**Comment by mjs2600** [comment]
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mutual_info_score.html

**Comment by jlmcgehee21** [comment]
This may be finished.  I'd like to know of a good way to check it (mathematically, not programmatically) before we cross it off though.

**Comment by mjs2600** [comment]
I just made the values negative. Looks great, thanks!
