### ISSUE TITLE
Implement Prim's Algorithm

### ISSUE THREAD

**Issue by mjs2600** [mjs2600/mimicry#5]

**Comment by mjs2600** [comment]
@jlmcgehee21 is this done?

**Comment by jlmcgehee21** [comment]
I very much hesitate to say done.  Prim's is a very popular algorithm.  There are tons of google hits for "Python Prim's Algorithm" .  I just picked one that looked relatively object oriented.  This is AN implementation of Prim's.  Don't know if it is the best one for use with the overall MIMIC algo.

**Comment by mjs2600** [comment]
I think we have this figured out now.
